server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: cluster