server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka
spring:
  application:
    name: cluster